/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface AlexaQuickLink {
        "rel"?: string;
        /**
          * Your skill id
         */
        "skillId": string;
        "target"?: string;
    }
}
declare global {
    interface HTMLAlexaQuickLinkElement extends Components.AlexaQuickLink, HTMLStencilElement {
    }
    var HTMLAlexaQuickLinkElement: {
        prototype: HTMLAlexaQuickLinkElement;
        new (): HTMLAlexaQuickLinkElement;
    };
    interface HTMLElementTagNameMap {
        "alexa-quick-link": HTMLAlexaQuickLinkElement;
    }
}
declare namespace LocalJSX {
    interface AlexaQuickLink {
        "rel"?: string;
        /**
          * Your skill id
         */
        "skillId"?: string;
        "target"?: string;
    }
    interface IntrinsicElements {
        "alexa-quick-link": AlexaQuickLink;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "alexa-quick-link": LocalJSX.AlexaQuickLink & JSXBase.HTMLAttributes<HTMLAlexaQuickLinkElement>;
        }
    }
}
